import type { Metadata } from "next";
import { Geist } from "next/font/google";
import "./globals.scss";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.className}`}>
        <div style={{ display: 'flex', justifyContent: 'space-around', padding: '10px', backgroundColor: 'blue' }}>
          <Link href={'/products'}>Products</Link>
          <Link href={'/checkout?token=sdfsadf34ewfef234defe3242srsdfsd'}>Checkout</Link>
          <Link href={'/merchant'}>Merchant</Link>
        </div>
        {children}
      </body>
    </html>
  );
}
